version: "2"

services:
  db:
    image: mysql
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./sql/data/:/var/lib/mysql

  redis:
    image: redis

  app:
    build: .
    command: >
      sh -c '
      rake resque:start_workers;
      bundle exec rails s -p 3000 -b 0.0.0.0;
      '
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /Users/martinhinge/Pictures/ROR_PT/phototank:/Users/martinhinge/Pictures/ROR_PT/phototank
    ports:
      - "3000:3000"
    depends_on:
      - db
