default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: db
  port: 3306



development:
  <<: *default
  database: phototank

test:
  <<: *default
  database: phototank_test

production:
  <<: *default
  database: phototank_prod
