default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  database: <%= ENV["MYSQL_DATABASE"] %>
  host: <%= ENV["MYSQL_HOST"] %>
  port: 3306



development:
  <<: *default


test:
  <<: *default
  

production:
  <<: *default
