:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
development:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - utility
  - import

:schedule:
  SchedulerMasterImport:
    cron: '0/30 * * * * *'
    class: SchedulerMasterImport
